baseURL = "https://rot.my.id/"
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "K.H Oirot"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
version = "0.2.X"

enableRobotsTXT = true
enableInlineShortcodes = true
enableEmoji = true
[params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
       index = ""
        appID = ""
        searchKey = ""

  # HEADER
[params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Rot"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "<i class='fas fa-om fa-fw'></i> "
      # you can add extra information after the name (HTML format is supported), such as icons
      post = " "
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = true        


 #   HOME
 [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/lol.png"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "rot"
      # subtitle shown in home page
      subtitle = " <b> Hai ! </b>   ini adalah blog sederhana saya."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false     
  # Footer config
  [params.footer]
    enable = true
    custom = 'KEROT'
    hugo = true
    copyright = true
    author = true
    since = 2020
    icp = ""
    #license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
 
 [params.section]
    # special amount of posts in each section page
    paginate = 15
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 15
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # MENU      
[menu]
  [[menu.main]]
    identifier = "Posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "Categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "About"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "telegram"
    pre = "<i class='fab fa-telegram fa-fw'></i>"
    post = ""
    name = ""
        url = "https://t.me/keroot"
        title = "telegram"
        weight = 4

[params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = "KEroot"
        logoUrl = ""


  [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = true

 [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        # LoveIt NEW | 0.1.1
        enable = true
        # Disqus shortname to use Disqus in posts
        shortname = "kroto"
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[permalinks]
  posts = ":slug/"